"""empty message

Revision ID: b9c7b92f200c
Revises: 
Create Date: 2023-01-28 10:05:42.054840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c7b92f200c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('flightNumber', sa.Integer(), nullable=False),
    sa.Column('departureAirport', sa.String(length=12), nullable=True),
    sa.Column('arrivalAirport', sa.String(length=12), nullable=True),
    sa.Column('flightDate', sa.String(length=10), nullable=True),
    sa.Column('aircraft', sa.String(length=12), nullable=True),
    sa.Column('pax_available', sa.Integer(), nullable=True),
    sa.Column('pax_booked', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('flightNumber'),
    sa.UniqueConstraint('arrivalAirport'),
    sa.UniqueConstraint('departureAirport')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('systemInfluence', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('senha', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('flights')
    # ### end Alembic commands ###
